openupm/openupm-cli

src/utils/error-type-guards.ts
Seems like I imported the incorrect error type here and did not notice
=> fix: incorrect error type

src/cli-parsing.ts, src/cli.ts, src/cmd-add.ts, src/cmd-login.ts, src/registry-client.ts, src/utils/pkg-manifest-io.ts
Both in symbol names and comments
=> refactor: fix typos

.eslintignore
=> chore: incorrect path in eslint ignore

src/types/upm-config.ts, src/utils/env.ts
Extract helper functions for getting auth-information from UPMConfig objects into the upm-config module, so they are close to other  UPMConfig related functions.
=> refactor: extract local helper function

tsconfig.build.json, tsconfig.json
Two small improvements for tsconfigs. Please check the commit messages.
=> conf: improve build tsconfig

src/cmd-login.ts
Add type for the return of `npmLogin`.
=> refactor: type npm-login result

package-lock.json
Run `npm audit fix`. No breaking changes were installed.
=> deps: bump various dependencies

src/types/package-manifest.ts, test/data-packument.ts
Refactor `PackageManifest` type to be immutable/readonly.
=> refactor: make package-manifest type readonly

src/utils/env.ts
Refactor to make `Env` type readonly/immutable.
=> refactor: make env type readonly

src/cmd-login.ts, src/utils/upm-config-io.ts
Refactors to simplify the code that stores upm-auth
=> refactor: simplify upm-auth storing

src/common-errors.ts, src/error-logging.ts, src/utils/env.ts, src/utils/project-manifest-io.ts, src/utils/project-version-io.ts, test/project-manifest-io.test.ts
Extract a utility function for loading the projects editor-version from ProjectVersion.txt to `project-version-io.ts`.
=> refactor: extract project-version load function

src/types/domain-name.ts, test/domain-name.test.ts
This PR removes a function that is no longer used anywhere.
=> refactor: remove unused code

src/types/editor-version.ts
Specifies the type of a function explicitly.
=> refactor: specify type explicitly

test/setup/unity-project.ts
The `tryGetManifest` function was never used outside `unity-project.ts`.  Removed the function and replaced its only use.
=> refactor: remove function

src/cmd-login.ts, src/cmd-search.ts
This is a continuation of #170. Seems like I missed a few functions.
Missed `project-version-io/tryLoadProjectVersion` on purpose in this PR, to avoid conflict with #178.
=> refactor: use async result

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-login.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/domain-name.test.ts, test/editor-version.test.ts, test/env.test.ts, test/npm-client.test.ts, test/package-id.test.ts, test/package-reference.test.ts, test/package-url.test.ts, test/packument.test.ts, test/project-manifest-io.test.ts, test/project-manifest.test.ts, test/registry-url.test.ts, test/scoped-registry.test.ts, test/semantic-version.test.ts, test/upm-config-io.test.ts, test/upm-config.test.ts
Currently some tests use anonymous-style functions and others arrow-style functions for describe and it blocks.
This PR makes it so that arrow functions are used everywhere.
=> style: standardize test function style

src/cmd-login.ts, src/utils/file-io.ts, src/utils/project-manifest-io.ts, src/utils/upm-config-io.ts, test/file-io.test.ts
This is a continuation of #178. This PR now adds an equivalent file-write function.
=> refactor: result-based file-write

test/npm-client.test.ts
Add tests for `npm-client`'s `addUser`.
=> test: add-user tests

test/npm-client.test.ts
Add tests for `npm-client trySearch`
=> test: add tests

test/npm-client.test.ts
Add tests for `npm-client tryGetAll`
=> tests: add tests

src/cmd-login.ts, src/domain/npmrc.ts, src/io/npmrc-io.ts, test/cmd-login.test.ts, test/npmrc.test.ts
Extract function for setting tokens in npmrc to own module.
=> refactor: extract npmrc domain logic

src/cmd-login.ts
Another refactor to pull up logs to bring them into cmd functions.
=> refactor: pull up log

src/cmd-login.ts
The npmLogin function did not really contribute enough to be it's own function. Merged it into the login function
=> refactor: merge function

src/io/upm-config-io.ts, src/utils/process.ts
=> refactor: child-process logic

src/io/upm-config-io.ts
Simplify async-result creation
=> refactor: upm-config dir logic

src/io/upm-config-io.ts, src/utils/env.ts, test/env.test.ts, test/upm-config-io.test.ts
Use result for return type. Also add test for it.
=> refactor: upm-config load result

src/io/upm-config-io.ts, src/io/wls.ts, test/env.test.ts, test/wsl.test.ts
Extracts logic for interacting with wsl to it's own module. Also adds tests for it.
=> refactor: extract wsl logic

test/cmd-add.test.ts, test/jest.d.ts, test/log.mock.ts
Adds a few small improvement to the log matcher
=> test: improve log matcher

src/cli/cmd-remove.ts
Makes removing multiple packages an atomic operation, as was recently implemented for the add command. See #234 for a longer explanation.
=> feat: atomic package remove

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/packument.test.ts
Use arrow functions everywhere for tests.
=> test: consistent function style

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/env.test.ts, test/project-version-io.mock.ts
Adds a mocking mechanism for the projects editor-version that does not involve a file-system.
=> test: mock project-version-io

test/project-manifest-io.test.ts
Use mocking instead of real file-system.
=> Improve project manifest io test

src/cli/cmd-add.ts, src/cli/cmd-remove.ts, src/cli/error-logging.ts
Move error-logging module into cli folder, since it is concerned with cli
=> refactor: move file

src/cli/cmd-add.ts, src/domain/scoped-registry.ts, test/scoped-registry.test.ts
Extract local helper function into relevant module and add a test.
=> refactor: extract helper function

src/cli/cmd-view.ts
Use the `tryResolve` function in cmd-view instead of directly using the fetch-service.
=> refactor: use resolve in cmd-view

test/cmd-remove.test.ts
Improve cmd-remove tests. The new tests test all outcomes. They also only mock direct dependencies, thus requiring less setup.
=> test: improve cmd-remove tests

test/add-user.test.ts, test/fetch-packument.test.ts, test/registry-client.mock.ts
Move functions for mocking registry-client results to own module.
=> refactor: extract module

src/cli/cmd-add.ts, src/cli/cmd-view.ts, src/cli/index.ts, src/packument-resolving.ts, src/services/dependency-resolving.ts, src/services/resolve-remote-packument.ts, test/cmd-add.test.ts, test/cmd-view.test.ts, test/packument-resolving.mock.ts, test/resolve-remote-packument.test.ts
Extract logic to resolve a remove packument to it's own service function. This allows for easier testing.
=> refactor: resolve-packuments service

src/cli/cmd-search.ts
Make functions local. This allows to use dependencies from closure instead of them having to be injected.
=> refactor: search cmd

src/domain/packument.ts, src/packument-resolving.ts, test/domain/packument.test.ts
Extract utility function for getting a packument-version from a packument.
=> refactor: extract utility function

src/services/dependency-resolving.ts
Use tuple instead of object for unprocessed/processed entries. This makes the code slightly shorter
=> refactor: dependency-resolve logic

src/cli/cmd-add.ts, src/services/fetch-packument.ts, src/services/resolve-remote-packument.ts
Add type alias for packument-fetch errors.
=> refactor: add type alias

src/services/dependency-resolving.ts
Refactor dependency-resolve function. The primary changes are:
- Requiring entry versions to be resolved semantic versions. This means that we can remove some checks.
- Invert the `isInternal` if. We now early-out for built-in packages, making the function less nested and allowing us to use more constants.
=> refactor: simplify dependency-resolving

src/cli/index.ts, src/io/upm-config-io.ts, src/services/upm-auth.ts
Extract a service style function for saving upm configs.
=> refactor: extract service function

.github/workflows/ci.yml, src/io/project-version-io.ts, test/e2e/add.e2e.ts, test/e2e/check/project-manifest.ts, test/e2e/run.ts, test/e2e/setup/directories.ts, test/e2e/setup/project.ts
This PR adds some e2e tests for the add command.
=> test: add-command e2e tests

src/cli/index.ts, src/domain/domain-name.ts, src/io/check-page.ts, src/io/check-url.ts, src/services/built-in-package-check.ts, src/services/dependency-resolving.ts, src/services/unity-package-check.ts, test/domain/domain-name.test.ts, test/e2e/add.e2e.ts, test/e2e/deps.e2e.ts, test/io/check-url.test.ts, test/services/built-in-package-check.test.ts, test/services/unity-package-check.test.ts
Attempt to solve issues involving built-in packages, such as #133 and #155.
See #363 for a discussion on the solution approach used in this PR.
=> feat: built-in package resolution

test/e2e/deps.e2e.ts
=> test: add more deps e2e tests

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/dependency-logging.ts, src/domain/dependency-graph.ts, src/services/dependency-resolving.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts, test/domain/dependency-graph.test.ts, test/e2e/add.e2e.ts, test/services/dependency-resolving.test.ts
=> fix: bad version in primary registry issue

.github/workflows/ci.yml
Bump version of actions to get rid of deprecation warnings
=> deps(ci): bump actions

src/services/dependency-resolving.ts, test/e2e/add.test.ts
See https://github.com/openupm/openupm-cli/issues/392
This fixes the issue of sometimes not adding scopes for all dependencies when adding packages. For a detailed explanation please take a look at the issue.
=> fix: partially resolved dependencies

package-lock.json
Run `npm update` to bump non-breaking dependencies
=> deps: npm update
