README.md, lib/cli.js, lib/cmd-add.js, lib/core.js, test/test-cmd-add.js
Added the option `-t` and `--testables` to add the package name to the `testables` array.
=> Added Test option to package add

package.json
With npm v6, we were allowed to run openupm like `npx openupm-cli add ...`. But npm v7 had some changes which broke this functionality. It is still possible to call it as `npx -p openupm-cli openupm add ...` but that is verbose. 
From [NPM docs](https://docs.npmjs.com/cli/v7/commands/npm-exec#description):
>  If no --package options are provided, then npm will attempt to determine the executable name from the package specifier provided as the first positional argument according to the following heuristic:
> - If the package has a single entry in its bin field in package.json, or if all entries are aliases of the same command, then that command will be used.
> - If the package has multiple bin entries, and one of them matches the unscoped portion of the name field, then that command will …
=> fix: allow running cli with npx v7

.eslintrc.js
When attempting to fix eslint rules in file, the following error appeared
```Error: "prettier/vue" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21```
Reading the linked changelog, it seemed the fix was to simply only use the prettier/recommended extension. Simplified eslintrc to reflect this.
=> fix: eslint-prettier error

package-lock.json, package.json, src/cmd-add.ts, src/cmd-search.ts, src/cmd-view.ts, src/types/global.ts, src/utils/pkg-info.ts, test/manifest-assertions.ts, test/mock-console.ts, test/mock-registry.ts, test/mock-work-dir.ts, test/test-cmd-add.ts, test/test-cmd-deps.ts, test/test-cmd-login.ts, test/test-cmd-remove.ts, test/test-cmd-search.ts, test/test-cmd-view.ts, test/test-env.ts, test/test-manifest.ts, test/test-pgk-info.ts, test/test-registry-client.ts, test/types.ts, test/utils.ts
This PR was originally meant to introduce property-based tests (see https://github.com/openupm/openupm-cli/issues/59). After some experiments it did not seem to add to much test security, so this was abandoned (Notice fast-check dependency was added and later removed)
Instead this PR includes various small changes that can be summarized with:
- Fixed a few small type errors in the actual implementation code, based on type usage in tests (For example make some properties optional)
- Add typings in tests where applicable
- Introduce/refactor helper functions and types for
- Mock package registry
- Mock console
- Mock manifest
- Mock work directory
- Deduplicate a lot of code by adding helper
- Split `utilities.ts` and group common functionality in new modules
- Small dev-dependency version …
=> refactor: misc improvements in tests

src/cmd-add.ts, src/cmd-deps.ts, src/cmd-login.ts, src/cmd-remove.ts, src/cmd-search.ts, src/cmd-view.ts, src/registry-client.ts, src/types/pkg-manifest.ts, src/utils/env.ts, src/utils/pkg-manifest-io.ts, src/utils/upm-config-io.ts, test/manifest-assertions.ts, test/mock-work-dir.ts, test/test-cmd-add.ts, test/test-cmd-remove.ts, test/test-env.ts, test/test-pkg-manifest-io.ts, test/test-registry-client.ts
This is a preparation refactor for the next PR where I want to tackle CLI validation. After starting with that I noticed, that I would like to do validation on `env` stuff before we even get inside the cmd-function. To make implementation of that easier `env` was extracted all the way up into these cmd-functions so it can easily be moved one more step up into the cli-logic.
Besides some other small refactors, this pull requests cleans up the env logic in three major ways:
Some properties, such as `color` are only ever used inside the `parseEnv` function and can be removed from the `env` object.
Also `env` currently stored all registry auth information even though you will only ever need the one for the registries that are currently in use. This was also cleaned up.
Instead of referencing …
=> refactor: de-global env

src/cmd-add.ts, src/cmd-search.ts, src/cmd-view.ts, src/registry-client.ts, src/types/domain-name.ts, src/types/editor-version.ts, src/utils/string-utils.ts, tsconfig.json
The [noUncheckedIndexedAccess](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) flag in tsconfig is not enabled by default when using `strict: true`, so it was not enabled until now. Enabled it for safer value access from records and fixed resulting warnings.
=> refactor: enable record undefined checks

src/registry-client.ts
Instead of using string, we can see in the code that it will always be one of a few values. This allows the compiler to better check on the other side if we have checked all posibillities
=> refactor: add better typing for string property

src/utils/error-type-guards.ts
This reverts a0f1abea67a42238e17c1bb8c300661147ead81c. As it turns out ErrnoException was used on purpose, because that type includes the `code` property.
A comment was added in order to make this more clear.
=> fix: type error

package-lock.json, package.json
Since the project used node 16, we should also use the types for node 16
=> desp: install node types matching node version

package-lock.json, package.json, src/cli-parsing.ts, src/cli.ts
- Bumps commander
- Adds dependency for better typings for commander
- Adds parsing / validation functions for arguments / options
This introduces checks, such as making sure, that when calling `openupm add` the package argument is a valid package name. 
This PR does not include any new tests. It would be nice to be able to test the app on the cli level, but further refactors are necessary for that.
=> feat: basic cli-argument validation

test/data-pkg-manifest.ts, test/test-domain-name.ts
This fixes two warnings that were missed during 4cbcd8daced03820f47ff3949eef19ab8bcd11b8
=> fix: misc undefined ts errors

src/types/editor-version.ts, test/test-editor-version.ts
The `version` parameter of `tryParseEditorVersion` is nullable needlessly. Made it non-nullable in order to simplify code. Also removed corresponding test.
=> refactor: remove null check

src/cmd-add.ts, src/cmd-search.ts, src/registry-client.ts, src/types/editor-version.ts, src/utils/env.ts
Mostly
- Commented out code
- Eslint commands that don't do anything
- Type descriptions which are now handled through TS
=> refactor: remove outdated comments

test/mock-env.ts, test/test-cmd-login.ts, test/test-upm-config-io.ts
Add a mock-env utility for testing with a mocked `process.env`. Also rewrote some tests to use this new functionality.
=> test: mock-env

src/utils/env.ts, src/utils/upm-config-io.ts, test/test-env.ts
An error was introduced a while ago where npm-auth loaded from .upmconfig would be discarded and null always returned. This was fixed. Also added a few tests to test for this behaviour-
=> fix: npm auth null

package.json, tsconfig.build.json, tsconfig.json
Previously we had a separate ts-config for tests. This was because we don't want test code to be emitted to lib.
This however caused issues with WebStorm, at least for me, because the IDE was not capable of correctly tracking two ts-configs live.
The fix is to use one ts-config for the whole projects (including tests), but then have a separate ts-config just for building, which extends the first one, but excludes tests.
Inspired by: https://stackoverflow.com/a/60223923
=> chore: better ts-config

.idea/jsLibraryMappings.xml
This was auto-generated after enabling node-support in WebStorm. Not quite sure what it does, but maybe it is useful to other WebStorm users.
=> chore: idea file for including node

package-lock.json, package.json
Because `@commander-js/extra-typings` had typings in the name I incorrectly thought it was a dev-only dependency, but it needs to be a regular dependency instead.
See https://github.com/openupm/openupm-cli/issues/87
=> fix: dependency was dev-dependency

src/registry-client.ts, src/types/another-npm-registry-client.d.ts
Improves type declaration for `another-npm-registry-client`. Previously my IDE did not give good intellisense for its types and I guessed it was somewhat incorrectly declared. I'm not sure I did it correct this time either, but at least everything has the correct color and I get intellisense, so thats good.
=> refactor: improve type declaration

.github/workflows/ci.yml, package.json
Adds a second test script for the project.
- `test:quick` runs test without type-checking
- `test:full` fully compiles ts before running tests, helping to uncover errors
Adjusted the cli to run `test:full`.
=> chore: additional test script

src/cmd-add.ts, src/types/editor-version.ts, src/types/upm-config.ts, test/test-editor-version.ts, test/test-upm-config.ts
Refactor functions which throw only one kind of error into functions that return `null` on failure instead. That way the client code can handle the issue without `try/catch`.
=> refactor: null instead of error

.idea/openupm-cli.iml
Configuration for jetbrains IDEs to exlude `lib` folder from indexing etc.
=> conf: idea exclude lib folder

src/cmd-login.ts, src/types/pkg-manifest.ts, src/types/registry-url.ts, src/types/upm-config.ts, src/utils/string-utils.ts, test/test-cmd-login.ts, test/test-registry-url.ts, test/test-upm-config.ts
See https://github.com/openupm/openupm-cli/issues/29
This PR ensures that all registry-urls inside the app-domain have **no trailing slash**. They are also saved like this to the `.upmconfig.toml`.
When querying for a registry-auth from the `upmconfig`, the program will now search for the registry-url both with and without the trailing slash to find it more reliably.
Added tests to ensure this behavior.
=> fix: trailing slash issue when finding auth in upmconfig

src/utils/project-manifest-io.ts
Currently the app crashes when trying to save the project-manifest if the target folder does not exist. This can be annyoing in test scenarios.
This fix creates the [Project]/Packages folder if it does not exist.
=> fix: manifest save crash

src/cmd-add.ts, src/cmd-deps.ts, src/cmd-view.ts, src/registry-client.ts, test/test-registry-client.ts
Calls to `fetchPackument` always create a short-lived instance of `NpmClient`. This probably has no big impact in performance, but it seems off. Extracted the client as a parameter. Now an `NpmClient` instance lives for the duration of a cli-command.
=> refactor: extract npm client param

src/types/project-manifest.ts, src/utils/project-manifest-io.ts
The functions responsible for ProjectManifest io took the path to the projects root directory, but always called it "work directory" or similar. Renamed the parameters to "projectPath" to better reflect their actual meaning. Also adjusted a few corresponding js-docs.
=> refactor: rename function params

src/cmd-search.ts, src/output-formatting.ts, src/types/packument.ts
Extracts logic for formatting packuments as a table to a separate module. The main benefits are:
- The logic does not clutter the `cmd-search` module
- Formatting logic can be reused by other commands
- Other output formatting logic now has a module where it can be grouped
=> refactor: extract table formatting

README.md
Autogenerated HTML code in Readme has some obsolete attributes. I don't think we care about that right now, so the warning was disabled.
=> chore: suppress warning

src/utils/env.ts
Check if content of ProjectVersion.txt has correct shape and contains m_EditorVersion before access. Throw an explicit error if not.
=> refactor: safe access property on unknown

CHANGELOG.md, README.md, src/utils/process.ts, tsconfig.build.json, tsconfig.json
=> docs: fix grammar issues

package-lock.json, package.json
Webstorm was marking version 2.0.1 as a security risk. Bumped to fix warning.
=> deps: bump yaml

test/test-cmd-login.ts, test/test-project-manifest-io.ts
Tests would fail on Windows, because of the different path-separators to Linux. Adjusted tests to take os into account.
=> fix: path issues on windows

src/cmd-add.ts, src/types/scoped-registry.ts, test/test-scoped-registry.ts
Logic for adding scope to scoped registry was somewhat duplicated. Partly it was inside `scoped-registry/addScope` and then also replicated in `cmd-add`. Refactored so `cmd-add` also used the `addScope` function.
=> refactor: reuse function

src/cmd-login.ts, src/types/upm-config.ts, test/test-upm-config.ts
Refactor `UPMConfig` and related types to be immutable/readonly. Adjusted usages accordingly and add tests.
=> refactor: make upm-config types readonly

src/cmd-login.ts, src/types/options.ts
Refactor to make `CmdOptions` and related types readonly/immutable.
=> refactor: make options type readonly

src/types/packument.ts, test/data-packument.ts
Refactor to make `UnityPackument` and related types readonly/immutable.
=> refactor: make unity-packument type readonly

src/registry-client.ts
`NpmClient.rawClient` was never used. This PR removes it.
=> refactor: remove unused property

src/cmd-add.ts, src/cmd-view.ts, src/registry-client.ts, src/utils/record-utils.ts
Add eqivalents for `Object.entries` and `Object.keys` that preserve key types.
=> refactor: add record utility functions

src/registry-client.ts
Extracted a few utility types and functions to clean up the registry-client cache logic.
=> refactor: clean-up registry-client cache logic

src/utils/upm-config-io.ts
The io code for upm-config was using sync io functions inside async functions. Adjusted to use the async version of these functions.
=> refactor: use async functions in upm-config io

src/cmd-add.ts, src/cmd-remove.ts, src/cmd-search.ts, src/registry-client.ts
Type array variables which are initialized to empty arrays, so they don't default to `any[]`
=> refactor: type empty arrays

src/types/editor-version.ts, test/test-editor-version.ts
A few small refactors to improve the `EditorVersion` type.
=> refactor: clean up editor-version

src/cmd-add.ts, test/project-manifest-assertions.ts, test/test-cmd-add.ts
Not create scopedRegistry when scopes are empty.
Possible when specified `@git`, `@htts`, and `@file` with `add` subcommand.
fixed #134
=> Fix make not create scopedRegistry when scopes are empty

src/cmd-add.ts, src/cmd-login.ts, src/cmd-remove.ts, src/logger.ts, src/registry-client.ts, src/types/scoped-registry.ts, src/utils/project-manifest-io.ts
Use `===` everywhere to avoid undwanted type coersion.
=> refactor: normalize equality operator

src/packument-cache.ts, src/registry-client.ts
Extract the packument caching logic into its own module in preparation for also using it in the `cmd-add`.
=> refactor: extract cache

src/cmd-add.ts, src/cmd-deps.ts, src/registry-client.ts
This refactor splits the `Dependency` type into multiple sub-types to ensure no properties are shared needlessly. This is in preparation for more changes in packument and dependency resolution.
=> refactor: split dependency

src/cmd-login.ts, src/cmd-search.ts, src/cmd-view.ts, src/packument-resolving.ts, src/registry-client.ts, test/test-registry-client.ts
The `NpmClient` type now has the task of abstracting all communication with npm registries. It builds and sends requests and interprets responses.
=> refactor: move npm functionality into npm-client

src/types/project-manifest.ts, src/utils/project-manifest-io.ts, test/test-cmd-remove.ts, test/test-project-manifest-io.ts
This addresses #153.
Now we prune empty scoped-registries before saving the manifest.
=> fix: empty scoped-registry after remove

src/cmd-add.ts, src/cmd-remove.ts, src/types/project-manifest.ts, src/utils/project-manifest-io.ts, src/utils/record-utils.ts, test/data-project-manifest.ts, test/setup/unity-project.ts, test/test-project-manifest-io.ts, test/test-project-manifest.ts
This PR makes all properties and property types of the `ProjectManifest` type readonly. This way it is more in line with other immutable object types in the project.
=> refactor: make project-manifest type readonly

src/packument-cache.ts
The packument cache types were already used in an immutable way. To formalize this they are now also declared as immutable
=> refactor: make type readonly

jest.config.js, package-lock.json, package.json, test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-login.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/domain-name.test.ts, test/editor-version.test.ts, test/env.test.ts, test/jest.d.ts, test/mock-console-assertions.ts, test/mock-console.ts, test/npm-client.test.ts, test/package-id.test.ts, test/package-reference.test.ts, test/package-url.test.ts, test/packument.test.ts, test/project-manifest-assertions.ts, test/project-manifest-io.test.ts, test/project-manifest.test.ts, test/registry-url.test.ts, test/scoped-registry.test.ts, test/semantic-version.test.ts, test/upm-config-io.test.ts, test/upm-config.test.ts
Migrates the test-suite from should to jests builtin assertion library. This also includes adding a few custom matchers.
=> refactor: use jest for assertion

src/cmd-add.ts, src/cmd-remove.ts, src/types/project-manifest.ts, src/types/scoped-registry.ts, src/utils/array-utils.ts, test/data-project-manifest.ts, test/project-manifest-io.test.ts, test/project-manifest.test.ts, test/scoped-registry.test.ts
Refactors the `ScopedRegistry` type to be immutable/readonly. This way it is aligned with other types which are now also mostly immutable.
Also adds a utility function `mapScopedRegistry` to modify a scoped-registry inside a manifest.
=> refactor: make scoped-registry type readonly

src/cmd-add.ts, src/cmd-remove.ts, src/error-logging.ts, src/utils/project-manifest-io.ts, test/project-manifest-io.test.ts
Currently, logging logic is spread out across the whole project. In my opinion logging should only be done in the cli parts of the application to make the rest more technology agnostic and testable.
This PR moves logging for `project-manifest-io` into utility functions which are used from cmd functions instead of directly inside the io functions.
I plan to do more refactors for other parts of the project with the goal of only having logs inside cmd functions.
=> refactor: no logs in manifest-io

src/cmd-add.ts, src/cmd-deps.ts, src/cmd-remove.ts, src/dependency-resolving.ts, src/types/domain-name.ts, src/types/package-id.ts, src/types/package-reference.ts, src/types/registry-url.ts, src/types/scoped-registry.ts, src/types/semantic-version.ts, src/utils/env.ts, src/utils/prompts.ts, test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-login.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/data-packument.ts, test/data-project-manifest.ts, test/domain-name.test.ts, test/env.test.ts, test/mock-registry.ts, test/npm-client.test.ts, test/package-reference.test.ts, test/packument.test.ts, test/project-manifest-io.test.ts, test/project-manifest.test.ts, test/scoped-registry.test.ts, test/upm-config.test.ts
Currently the names of constructor functions often conflict with variable names. For example the constructor function for `ScopedRegistry` is called `scopedRegistry`. Often you would also like to call a variable of type `ScopedRegistry` `scopedRegistry`. Then there is a name-conflict. This is also true for other types/constructors.
In order to fix this issue `make` was prefixed to all constructor functions, i.e. `makeScopedRegistry`.
Another option would have been to capitalize constructor functions, i.e. `ScopedRegistry`, but that would conflict with the type name.
=> refactor: disambiguate constructors

src/cmd-add.ts, src/cmd-login.ts, src/cmd-remove.ts, src/cmd-search.ts, src/cmd-view.ts, src/dependency-resolving.ts, src/npm-client.ts, src/packument-resolving.ts, src/utils/env.ts, src/utils/project-manifest-io.ts, src/utils/project-version-io.ts, src/utils/upm-config-io.ts, test/npm-client.test.ts, test/project-manifest-io.test.ts, test/setup/unity-project.ts, test/upm-config-io.test.ts
`ts-results-es` includes an `AsyncResult` type which can replace `Promise<Result>` and allows for easier mapping.
This PR refactors return types to use `AsyncResult` in transformation-style functions.
=> refactor: use async-result type

src/types/package-id.ts, src/types/package-reference.ts, src/types/upm-config.ts, src/utils/string-utils.ts
In general I prefer to represent missing values using `null` instead of `undefined`. Refactor a function return to use `null`.
=> refactor: prefer null for return type

src/types/project-manifest.ts, test/project-manifest.test.ts
Rename function to better describe it's behaviour. The `addScopedRegistry` function can not only be used to add a scoped-registry to a manifest, but also to replace it. Changed name and documentation to reflect this.
=> refactor: rename function

src/common-errors.ts
Some classes and properties in the `common-errors.ts` file did not have JSDoc. Added where missing.
=> docs: missing error jsdoc

test/npm-client.test.ts
Tests ran through the env-parsing process pretty much for no reason. They just did it to obtain a registry-object for passing to the fetch function.
Instead of using env for that, we can just make a registry object for testing purposes and pass that directly.
=> refactor: simplify npm-client tests

src/cmd-login.ts, src/utils/file-io.ts, src/utils/project-manifest-io.ts, src/utils/project-version-io.ts, src/utils/upm-config-io.ts, test/file-io.test.ts
Currently different parts of the app use variations of `fs.readFile` for file-reading. In order to bring resulting errors into the result-based return values required for most functions they all have to do some form of try-catch. 
In order to deduplicate this, a utility function for file-reading was added which abstracts this away.
More PRs doing the same for other file-io functions coming soon.
=> refactor: use result-type for file-reads

src/utils/env.ts
Currently the `parseEnv` function is a bit of a mish-mash of high- and low-level logic, with logging and other stuff mixed in.
In a first step to clean up and also start splitting the function into more reusable parts, the logic for determining the individual properties of env were moved into separate functions.
This PR also makes the `parseEnv` function not use any `let` variables anymore.
=> refactor: split env parse

src/utils/env.ts
Currently we have a special error for when the cwd is not found (`CwdNotFoundError`). Really we don't need this special error.
We can just use `NotFoundError`.
=> refactor: merge errors

src/utils/data-parsing.ts, src/utils/project-manifest-io.ts, test/data-parsing.test.ts
Currently when we want to parse json we have to use `JSON.parse` and wrap the operation in a result manually.
This PR adds a result-based and type-safe json-parse function for convenience.
=> refactor: result json parse

jest.config.js, src/cmd-add.ts, src/cmd-deps.ts, src/cmd-login.ts, src/cmd-remove.ts, src/cmd-search.ts, src/cmd-view.ts, src/types/project-manifest.ts, src/utils/env.ts, test/env.test.ts, test/jest.d.ts, test/project-manifest.test.ts, test/setup/unity-project.ts
Completely rewrites env tests with three major goals:
- Decouple from actual fs and process (Only use mocks)
- Exhaustively test all possible outputs (Including logs and errors)
- Shorten/de-duplicate test code
Also introduces some minor changes inside `parseEnv`. Please check commit messages for more details.
=> refactor: env clean up

src/common-errors.ts, src/utils/error-type-guards.ts, src/utils/file-io.ts
`assertIsError` function was used to assert that objects were Node.js errors. But this disregarded that not all errors that occur in the program are Node.js errors, such as the one resulting from `JSON.parse`.
Created a separate assertion specifically for Node errors.
=> refactor: differentiate node error

src/cmd-add.ts, src/cmd-deps.ts, src/dependency-resolving.ts
Continuation of #168. Moves one logging call up into the containing cmd-functions
=> refactor: pull up log

package-lock.json, package.json, test/base64.test.ts
Since base64 encode/decode roundtrip should work regardless of input, it's a perfect use-case for a property-based test.
=> refactor: change test to prop test

src/types/domain-name.ts
We check a variable for null even though it will never be null. Removed that check.
=> refactor: simplify function

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/domain-name.test.ts, test/editor-version.test.ts, test/npm-client.test.ts, test/package-id.test.ts, test/package-reference.test.ts, test/packument.test.ts, test/project-manifest-io.test.ts
jest tests usually have the format of `it("should ...")`. Currently not all tests have this format.
Made a pass over all tests and standardize the labels.
=> test: use consistent test lables

src/cmd-add.ts, src/types/packument.ts, test/packument.test.ts
Extract logic for getting the editor-version string, e.g. "2020.3.1f1", from a packument-version, into it's own function.
=> refactor: extract helper function

src/types/another-npm-registry-client.d.ts, test/npm-client.test.ts
Mock the registry on a function level instead of redirecting network traffic. Also add test for errors.
=> refactor: npm-client test

src/cmd-login.ts, src/io/npmrc-io.ts, test/cmd-login.test.ts, test/npmrc-io.test.ts
Extract logic for loading and saving npmrc to it's own module.
=> refactor: extract npmrc-io

src/cmd-login.ts, src/io/upm-config-io.ts, src/logger.ts, src/utils/env-util.ts, src/utils/env.ts
Extract utility function for getting env variables. This allows for easier mocking.
=> refactor: extract env utility

src/cmd-login.ts, src/io/npmrc-io.ts, src/services/npmrc-token-update-service.ts, test/npmrc-token-update-service.test.ts
The logic to update npm-tokens inside a npmrc was part of the cmd-login module. It is my goal to only have cli relevant logic inside the cmd modules. So, I wanted to move this logic somewhere else.
Moved it to it's own service module. I want to have more service modules in the future, to encapsulate business logic that should not be inside cmd modules. Also added tests for it.
=> refactor: extract npm-token update service

src/io/home.ts, src/io/npmrc-io.ts, src/io/upm-config-io.ts, test/home.test.ts, test/npmrc-io.test.ts, test/upm-config-io.test.ts
Both the code for determening npmrc and upmconfig paths basically use the same logic for finding the users home path. This leads to some code duplication.
Extract helper function for finding user-home path. Also adjust tests to deduplicate.
=> refactor: home-path logic

src/io/upm-config-io.ts, src/utils/data-parsing.ts
Make a result-based toml parse function
=> refactor: use result-type for return

src/cli/cmd-add.ts, src/utils/env.ts, test/env.test.ts
This PR moves the logic for parsing the projects `EditorVersion` into `parseEnv`. That way it does not need to be repeated in cmds.
This also makes it easier to work on #225.
=> refactor: editor-version env

src/cli/cmd-add.ts, src/common-errors.ts, src/io/file-io.ts, src/io/special-paths.ts, src/io/upm-config-io.ts, src/npm-client.ts, src/packument-resolving.ts, src/services/builtin-packages.ts
Because of TS' structural typing some error types were actually considered the same type, especially the empty ones. This interfered with TS' ability to warn of unhandled errors.
To fix this a private unique field was added to all error types to better distinguish them.
=> refactor: strong error types

src/cli/cmd-login.ts, src/io/upm-config-io.ts, src/utils/env.ts, src/utils/process.ts, test/wsl.test.ts
`ChildProcessError`was just an alias to `childProcess.ExecException` which intern was basically just `Error` with a few extra optional properties. This caused `ChildProcessError` to basically be equal to `Error` which prevented TS  from doing some type-checking magic as it was equal to every other error type in the project (because they are also all subtypes of `Error`).
To prevent this made `ChildProcessError` a proper class.
=> refactor: strong child-process error

src/cli/cmd-remove.ts, src/domain/editor-version.ts, src/io/npmrc-io.ts, src/io/upm-config-io.ts, src/utils/env.ts, test/env.test.ts
Env now enforces that the project editor-version must be a patch version (eg. 2022.1.2f1). From what I can see ProjectVersion.txt always only contains a patch-version anyway.
=> refactor: better typing for env editor-version

src/cli/cmd-add.ts
Currently, when calling `add` with multiple packages, each will load, modify and save the project-manifest. This repeated loading and saving was necessary in case a package caused the app to crash, so that previous modifications would still be saved.
For a while now, the app should no longer crash in regular use. Instead it will return error objects. This means we can now safely load and save the manifest only once.
=> refactor: cmd-add manifest io

package-lock.json, package.json
This reverts commit b27edcbd7fbaa889a3f53d88c6c866bac6439d44 which bumped `@semantic-release`.
Seems like the new version requires a newer node version than we use.
=> fix: engine warning

test/cmd-add.test.ts, test/cmd-remove.test.ts, test/project-manifest-io.mock.ts, test/setup/unity-project.ts
Currently testing operations that modify the project-manifest rely on mocking or actually using a file-system. This makes test-parallelization difficult as well as generally making it harder to write tests.
This change introduces a mocking mechanism for the project-manifest which does not rely on a file-system.
=> test: improve project-manifest mock

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/env.test.ts, test/upm-config-io.mock.ts
Currently when mocking upm-config in tests we do this by using a file-system and actually creating the upm-config file.
This change introduces a mocking mechanism which does not involve a file-system.
=> refactor: mock upm-config-io

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts
Remove `.ts` from describe block names. For consistency.
=> test: rename describe blocks

package.json
Until now we had to run tests in sequence because they depended on the same base-dependencies (file-system, network).
Since now all tests are mocked to be completely independent, we can run them in parallel. This improves speed.
=> conf: parallelize tests

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-remove.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts, src/cli/index.ts, test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts
Currently cmd-functions create the services they use themselves. This makes it harder to test because service-creation logic needs to be mocked. Also it makes the dependencies for a cmd hard to find.
This PR refactores cmd functions so that services are injected into them. All services and cmd functions are now created inside `cli/index`.
=> refactor: inject services

src/cli/cmd-deps.ts, test/cmd-deps.test.ts
Clean up tests for cmd-deps. Mock direct dependencies in order to simplify necessary setup logic.
=> test: simplify deps test

src/cli/cmd-remove.ts, src/cli/cmd-view.ts
For the remove and view command users should not specify package versions. I.e. they should not use these commands like `openupm remove com.some.package@1.0.0`. If they do specify a version, then a message warning the user should be printed.
This message is currently incorrect. If a user would use the command as above it would print `please do not specify a version (Write only 'com.some.package@1.0.0').`. This log also includes a version, despite that that is the exact issue.
Fixed. Now the log will say `please do not specify a version (Write only 'com.some.package').`
=> fix: bad log

test/cmd-add.test.ts, test/packument-resolving.mock.ts
Replaces add-cmd tests with new ones which are improved  in the following ways:
- Test more scenarions
- Reduce test repetition
- Only mock direct dependecies
=> test: improve add-cmd tests

src/cli/index.ts, src/services/add-user.ts, src/services/fetch-packument.ts, test/add-user.test.ts, test/fetch-packument.test.ts
Refactors services which use the `another-nmm-registry-client` registry-client to get it injected instead of creating it themselves.
This improves mocking/testing.
=> refactor: inject registry-client

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-remove.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts, src/cli/index.ts, src/services/parse-env.ts, test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/parse-env.test.ts
Currently all cmd functions call `parseEnv`. When testing this we have to mock the whole `env` module.
In order to make mocking/testing easier, extract a service for parsing env that is injected.
=> refactor: extract service

test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/service.mock.ts
Extract helper function for mocking service functions. It makes it a little bit shorter.
=> refactor: extract helper  function

src/io/upm-config-io.ts, src/utils/data-parsing.ts, test/data-parsing.test.ts, test/upm-config-io.test.ts
Currently, errors for when json or toml can not be parsed are just a plain `Error`. This is problematic, because it messes with TS' ability to differentiate errors.
To fix this, this change introduces the `StringFormatError` which can be used if a string does not match a specific format.
=> refactor: add string-format error

src/cli/cmd-add.ts, src/cli/cmd-remove.ts, src/cli/index.ts, src/io/project-manifest-io.ts, test/cmd-add.test.ts, test/cmd-remove.test.ts, test/project-manifest-io.mock.ts, test/project-manifest-io.test.ts
The logic for loading project-manifests is currently directly called from within client functions. This makes it somewhat harder to mock.
This change makes it so that manifest-loading logic is a "service-style" function which needs to be injected into client services. This allows for easier mocking.
=> refactor: inject project-manifest load

test/add-user.test.ts, test/cmd-add.test.ts, test/cmd-deps.test.ts, test/cmd-remove.test.ts, test/cmd-search.test.ts, test/cmd-view.test.ts, test/fetch-packument.test.ts, test/get-all-packuments.test.ts, test/get-builtin-packages.test.ts, test/npmrc-auth.ts, test/parse-env.test.ts, test/project-manifest-io.test.ts, test/search-registry.test.ts
Currently test dependencies are exposed as a const array.
I realized it is more convenient to expose them as an object instead. That way you
- get intellisense for the property names
- can more easily only import required dependencies
=> refactor: dependency logic in tests

src/cli/cmd-add.ts, src/cli/cmd-remove.ts, src/cli/error-logging.ts, src/cli/index.ts, src/domain/scoped-registry.ts, src/io/project-manifest-io.ts, test/cmd-add.test.ts, test/cmd-remove.test.ts, test/project-manifest-io.mock.ts, test/project-manifest-io.test.ts
Currently the logic to write the project manifest to disk is directly used in client code. This makes mocking a little difficult.
This change makes it so that the write function is created in composition root and then injected into client code.
=> refactor: inject project manifest save

src/cli/cmd-add.ts, src/domain/editor-version.ts, src/domain/packument.ts, test/packument.test.ts
Currently the logic for establishing the target editor version for a package are split between `cmd-add` and `packument`.
Since this is only domain logic, moved it completely into `packument`.
=> refactor: package target editor

src/cli/cmd-add.ts
When adding a package the app will warn if the version inside ProjectVersion.txt is malformed. If multiple packages are added it will make this warning for each package.
This seems a bit redundant. Probably we should only log the warning once at the beginning of the add operation.
=> feat: deduplicate log

src/io/project-version-io.ts
Logic for creating ProjectVersion.txt used to be used in tests. Now this is all mocked, so we can remove this code.
=> refactor: remove unused code

src/io/project-version-io.ts, src/utils/data-parsing.ts, test/data-parsing.test.ts, test/project-version-io.test.ts
This PR extracts the logic for parsing yaml and wrapping in a result to it's own utility function. This allows for shorter client code.
=> refactor: yaml parse utility

src/io/upm-config-io.ts
`@returns` is preferred over `@return`.
=> docs: fix jsdoc warning

src/cli/cmd-login.ts, src/cli/index.ts, src/services/npm-login.ts, test/services/npm-login.test.ts
The `AddUserService` is responsible for logging in users into a npm registry.
The service and associated symbols were renamed to `NpmLoginService`  to better reflect this.
=> refactor: rename service

src/cli/cmd-add.ts, test/cli/cmd-add.test.ts
The error log for when a package version could not be found is currently incorrect.
When adding package `com.some.package@2.0.0` and the primary registry has the package, just not that version the app will still fail with "not found". This is because `com.some.package` does not exist at all in the upstream registry and that error overrides the first "version not found".
Fixed by checking which error  is more fixable and printing that. A missing version is more fixable than the package not existing at all.
=> fix: incorrect log

src/services/npm-login.ts, src/types/another-npm-registry-client.d.ts, test/services/npm-login.test.ts
npm-registry-client passes an `undefined` response when the request was not even sent or when we got no response. This caused uncaught errors when trying to access properties of `undefined`.
Adjusted usage.
=> fix: adjust incorrect typing

src/io/file-io.ts
Errors use a special property to distinguish themselves. The `IOError` type had an incorrect property value.
=> refactor: fix incorrect error distinction

src/cli/cmd-add.ts, src/cli/error-logging.ts, src/services/dependency-resolving.ts
Extract logging logic for `PackumentResolveError`s to own function that can more easily be reused.
=> refactor: extract logging logic

src/cli/cmd-add.ts, src/cli/dependency-logging.ts, src/services/dependency-resolving.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts
Currently the resolved dependencies have a flag indicating whether they are resolved from the primary or upstream registry.
To prepare for the case where the app might use n registries (#49) refactor to instead specify the package source.
=> refactor: dependency source logic

src/cli/cmd-view.ts, src/cli/index.ts, test/cli/cmd-view.test.ts
Cmd-view does not really need access to the resolve-packument service since that one is used for resolving specific versions, but cmd-view only needs the packument itself.
=> refactor: cmd view

src/cli/index.ts, src/services/get-all-packuments.ts, src/services/search-registry.ts, test/services/get-all-packuments.test.ts, test/services/search-registry.test.ts
The registry service takes a logger to log diagnostic information. These logs should not really be seen by the user and thus should not use the "front-end" logger.
=> refactor: remove unseen logs

src/cli/cmd-add.ts
The if that checks the reason why a dependency could not be resolved is not really necessary. In any case the handling code should be executed.
=> refactor: remove unnecessary if

src/cli/cmd-add.ts, src/domain/project-manifest.ts, test/domain/project-manifest.test.ts
This change extracts a utility function for checking if a manifest has a dependency.
Also adds test and a short explanatory comment where it is used.
=> refactor: extract utility function

src/cli/cmd-add.ts, src/domain/package-manifest.ts, src/domain/packument.ts, test/domain/data-project-manifest.ts, test/domain/package-manifest.test.ts, test/domain/packument.test.ts
Makes the `tryGetTargetEditorVersionFor` function more generic. Please see commit messages for more details.
=> refactor: make function generic

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/services/dependency-resolving.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts
Refactor dependency-resolve service to use result-based return. This way it integrates more nicely into the service eco-system.
=> refactor: use result return

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/services/dependency-resolving.ts
Currently the dependency resolve service expects the registries to check as two distinct parameters.
This change refactors it to allow it to use any number of sources instead.
=> refactor: dependency-resolve service

test/services/resolve-remote-packument.test.ts
The `ResolveRemotePackumentService` was not tested until now. Added tests. This service mostly just glues together other functions so we don't need that many tests.
=> test: add tests for service

src/packument-resolving.ts, src/services/resolve-remote-packument.ts, test/services/packument-resolving.mock.ts, test/utils/packument-resolving.test.ts
The `tryResolveFromPackument` function should be responsible for resolving a specific version from a packument. But currently it's signature also includes errors it can't really produce as well as having context, like the source, injected into it only to produce it as output.
This is not really necessary. We should keep this function simple and add context in the client functions. Refactored for this purpose.
=> refactor: make function more focused

src/cli/cmd-login.ts, src/cli/index.ts, src/io/file-io.ts, src/io/npmrc-io.ts, src/io/project-manifest-io.ts, src/io/project-version-io.ts, src/io/special-paths.ts, src/io/upm-config-io.ts, src/services/npmrc-auth.ts, src/services/parse-env.ts, src/services/upm-auth.ts, test/io/file-io.test.ts, test/io/npmrc-io.test.ts, test/io/project-manifest-io.test.ts, test/io/project-version-io.mock.ts, test/io/project-version-io.test.ts, test/io/special-paths.test.ts, test/io/upm-config-io.test.ts, test/services/fetch-packument.test.ts, test/services/npmrc-auth.test.ts, test/services/parse-env.test.ts
This change completes the process that I was working on over the last weeks where functions get side-effect functions injected into them instead of importing them directly.
This makes them easier to test as well as making dependencies between services clearer.
=> refactor: inject dependencies

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-search.ts, src/cli/error-logging.ts, src/io/upm-config-io.ts, src/services/dependency-resolving.ts, src/services/fetch-packument.ts, src/services/get-all-packuments.ts, src/services/resolve-latest-version.ts, src/services/resolve-remote-packument.ts, src/services/search-registry.ts, src/types/npm-registry-fetch.d.ts, src/types/npm-registry-fetch/lib/errors.d.ts, src/utils/error-type-guards.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts, test/cli/cmd-search.test.ts, test/services/fetch-packument.test.ts, test/services/get-all-packuments.test.ts, test/services/npm-login.test.ts, test/services/packument-resolving.mock.ts, test/services/registry-client.mock.ts, test/services/resolve-latest-version.test.ts, test/services/search-registry.test.ts
The declaration files for `npm-registry-fetch` package do not expose the error-class it throws when a fetch failed. Because of this, we wrote our own declaration file for it.
The declaration file was incorrectly written. It placed the error class into the packages `index` file even though it is inside `lib/errors`. After updating the declaration and relevant imports the error is now fixed.
See #319.
=> fix: bad declaration file

test/e2e/common.ts, test/e2e/help.test.ts, test/e2e/unknown.test.ts, test/e2e/version.test.ts
This PR adds some basic e2e tests that test the app on the CLI level. This first batch of tests is mostly just to see if it works as expected.
=> test: add basic e2e tests

.github/workflows/ci.yml, package.json, test/e2e/common.ts
Run e2e tests in own phase and folder. This will make it easier to mock install unity installations etc
=> test: e2e environment

src/cli/cmd-search.ts, src/cli/index.ts, src/io/all-packuments-io.ts, test/cli/cmd-search.test.ts, test/io/all-packuments-io.test.ts
Change the get-all-packuments service to an io function because it mostly just abstracts interaction with the outside world without contributing any business logic. Also renamed it to "fetchAllPackuments" to better fit with other similar functions.
=> refactor: all-packuments service to io

src/cli/cmd-search.ts, src/cli/index.ts, src/io/all-packuments-io.ts, src/io/npm-search.ts, test/cli/cmd-search.test.ts, test/io/npm-search.test.ts
The service for searching keywords on a npm registry is mostly an abstraction for an external library. It does not really have any business logic. As such it should be a io function and not a service.
=> refactor: npm search service to io

src/io/all-packuments-io.ts
In order to mix an index type with known properties the type declaration must be different. Fixed it. See https://stackoverflow.com/a/63430341/13219897
=> refactor: fix index type

src/io/all-packuments-io.ts
Was to greedy and skipped the tests in https://github.com/openupm/openupm-cli/commit/659f16c7287f728a98c53954cba12ddc80b03232. This actually breaked the code because deconstructing does not work anymore.
Seems like what i wanted to do in that change is not possible. https://github.com/openupm/openupm-cli/commit/659f16c7287f728a98c53954cba12ddc80b03232
=> refactor: revert previous fix

src/cli/cmd-add.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts, src/cli/index.ts, src/services/dependency-resolving.ts, src/services/resolve-latest-version.ts, src/services/resolve-remote-packument.ts, src/services/search-packages.ts, test/cli/cmd-search.test.ts, test/cli/cmd-view.test.ts, test/services/resolve-latest-version.test.ts, test/services/resolve-remote-packument.test.ts, test/services/search-packages.test.ts
This change extracts the business logic for searching packages into its own service making the search-cmd function now only concerned with cli related code.
Also improves tests to cover more scenarios.
=> refactor: extract search service

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/error-logging.ts, src/domain/packument.ts, src/packument-version-resolving.ts, src/services/dependency-resolving.ts, src/services/resolve-remote-packument-version.ts
The module and types related to resolving packument versions did not contain the "version" in their name.
=> refactor: rename types/module

src/cli/cmd-view.ts, src/cli/index.ts, src/services/resolve-remote-packument.ts, test/cli/cmd-view.test.ts, test/services/resolve-remote-packument.test.ts
This PR adds a service for resolving packuments by searching a list of source registries in order. For now this is only used in cmd-view (which has the nice effect of making the cmd function cli-logic only), but it could also be used in other places in the future, especially when it comes to #49.
=> refactor: resolve packument service

src/cli/cmd-login.ts, src/cli/index.ts, src/io/upm-config-io.ts, src/services/parse-env.ts, test/io/upm-config-io.test.ts, test/services/parse-env.test.ts
Currently we have a service function for determining the directory in which the upmconfig is located. On load and save the actual file path of the config is constructed from this directory.
There is no need for this delayed path construction. We can instead make the service resolve the actual path of the config file right away. This makes client code a little shorter.
=> refactor: upmconfig load logic

src/cli/cmd-login.ts, src/io/upm-config-io.ts, src/services/upm-auth.ts
Currently we return the path of the upm config file we modified after a save so that the path can be in logging. This is done because previously we only had access to the configs directory path in the client code.
Since #337 we also have access to the file path in client code and so dont need this return value.
=> refactor: clean up upm auth

src/cli/cmd-login.ts, src/cli/index.ts, src/services/login.ts, test/cli/cmd-login.test.ts, test/services/login.test.ts
Extract login logic into a separate service to keep the logic inside the cmd function focused on cli concerns. Also add tests for both the cli function and the new service.
=> refactor: extract login service

src/cli/error-logging.ts, src/common-errors.ts, src/io/builtin-packages.ts, src/io/file-io.ts, src/io/npmrc-io.ts, src/io/project-manifest-io.ts, src/io/upm-config-io.ts, src/services/parse-env.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts, test/cli/cmd-login.test.ts, test/cli/cmd-remove.test.ts, test/cli/cmd-view.test.ts, test/io/builtin-packages.test.ts, test/io/file-io.test.ts, test/io/npmrc-io.test.ts, test/io/project-manifest-io.mock.ts, test/io/project-manifest-io.test.ts, test/io/project-version-io.test.ts, test/io/upm-config-io.test.ts, test/services/login.test.ts, test/services/npmrc-auth.test.ts, test/services/parse-env.test.ts
Merge FsError and NotFoundError. This simplifies handling logic. Also remove references to node error from FsError in order to avoid leaking low-level information when not necessary.
=> refactor: fs error type

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-remove.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts, src/cli/error-logging.ts, src/common-errors.ts, src/io/special-paths.ts, src/io/upm-config-io.ts, test/cli/cmd-login.test.ts, test/io/npmrc-io.test.ts, test/io/upm-config-io.test.ts, test/services/npmrc-auth.test.ts
This PR adds some basic error logging for the error produced by the parse-env service.
=> feat: basic env error logging

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-search.ts, src/cli/dependency-logging.ts, src/cli/index.ts, src/io/builtin-packages.ts, src/io/file-io.ts, src/logging.ts, src/services/login.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts, test/cli/cmd-search.test.ts, test/io/builtin-packages.test.ts, test/io/file-io.test.ts, test/services/login.test.ts
This PR separates the logging functions for user-facing and debug logs. User-facing logs should only be made on the CLI layer while debug logs can be made everywhere. This way low-level errors which only get logged to the debug log don't need to be bubbled all the way up to the CLI layer.
=> refactor: separate user and debug logs

src/cli/error-logging.ts, src/cli/index.ts, src/io/builtin-packages.ts, src/io/common-errors.ts, src/io/file-io.ts, src/io/fs-result.ts, src/io/npmrc-io.ts, src/io/project-manifest-io.ts, src/io/project-version-io.ts, src/io/upm-config-io.ts, src/services/parse-env.ts, src/services/resolve-latest-version.ts, src/services/upm-auth.ts, test/cli/cmd-add.test.ts, test/cli/cmd-deps.test.ts, test/cli/cmd-login.test.ts, test/cli/cmd-remove.test.ts, test/cli/cmd-search.test.ts, test/cli/cmd-view.test.ts, test/io/builtin-packages.test.ts, test/io/fs-result.test.ts, test/io/node-error.mock.ts, test/io/npmrc-io.test.ts, test/io/project-manifest-io.mock.ts, test/io/project-manifest-io.test.ts, test/io/project-version-io.test.ts, test/io/upm-config-io.test.ts, test/services/login.test.ts, test/services/npmrc-auth.test.ts, test/services/parse-env.test.ts
Refactor logic for file-system related io errors. The main changes are:
- We now log all file-system errors when they happen using the debug logger. This way we don't need to bubble the errors all the way up to the cli layer.
- There are now two file-system error types as part of the domain. One for when a file is missing and one for everything else.
- The `FileMissingError` allows to pass a constant string which identifies the missing file ("ProjectVersion.txt", "ProjectManifest", ...). This way the error can be reused for different files but still be differentiated for better logging.
=> refactor: improve file-io errors

test/io/upm-config-io.test.ts, test/services/parse-env.test.ts
Some tests failed when running on windows, specifically because of different path separators. This is now fixed.
=> test: make os independent

src/cli/cmd-remove.ts, src/cli/error-logging.ts, src/cli/index.ts, src/common-errors.ts, src/packument-version-resolving.ts, src/services/dependency-resolving.ts, src/services/remove-packages.ts, src/services/resolve-latest-version.ts, src/services/resolve-remote-packument-version.ts, test/cli/cmd-deps.test.ts, test/cli/cmd-remove.test.ts, test/io/project-version-io.test.ts, test/services/packument-resolving.mock.ts, test/services/remove-packages.test.ts
This change extracts all business logic out of the remove command into its own service function. The cmd function is now only responsible for cli related logic.
This change also slightly changes the behavior of the remove command.
- Logs are rewritten
- Information about removed packages is printed all at once at the end when the atomic remove process is complete. Previously messages about removed packages were printed as soon as the in-memory manifest was modified. The command could still fail however and then these logs would be confusing.
=> feat: extract remove service

src/services/resolve-remote-packument.ts, src/utils/result-utils.ts, test/cli/cmd-add.test.ts, test/cli/cmd-login.test.ts, test/cli/cmd-remove.test.ts, test/cli/cmd-search.test.ts, test/cli/cmd-view.test.ts, test/io/builtin-packages.test.ts, test/io/project-manifest-io.mock.ts, test/io/project-manifest-io.test.ts, test/io/project-version-io.mock.ts, test/io/project-version-io.test.ts, test/io/upm-config-io.mock.ts, test/io/upm-config-io.test.ts, test/io/wsl.test.ts, test/services/determine-editor-version.test.ts, test/services/login.test.ts, test/services/parse-env.test.ts, test/services/remove-packages.test.ts, test/services/resolve-latest-version.test.ts, test/services/resolve-remote-packument-version.test.ts, test/services/resolve-remote-packument.test.ts, test/services/search-packages.test.ts
Writing `Ok(value).toAsyncResult()` is quite long. This change adds helper constructor functions for building async results. Both for ok and error results.
=> refactor: async result constructor

.github/workflows/ci.yml
Building the project is not necessary for unit tests. We can skip this step.
=> opt(ci): remove unnecessary ci step

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/index.ts, src/services/dependency-resolving.ts, test/cli/cmd-deps.test.ts
Currently, you can either pass a semantic version or "latest" to the dependency-resolve service. The service will then resolve the packages latest version if no semantic version was given.
This complicates the logic inside the service. For this reason, now the client calling the service needs to determine the latest version and pass it to the service.
=> refactor: dependency resolving logic

package-lock.json, package.json
A recent dependency inclusion of node-fetch caused issues, because I forgot to add it as a direct dependency.
We now depend on node-fetch@2.
Closes #371
=> fix: 371 error cannot find module node fetch

src/io/builtin-packages.ts, src/io/directory-io.ts, test/io/builtin-packages.test.ts, test/io/directory-io.test.ts
Convert the function for getting directory names into a service function that needs to be injected.
=> refactor: convert to service function

src/domain/project-manifest.ts, src/services/remove-packages.ts, src/types/another-npm-registry-client.d.ts, test/domain/package-manifest.test.ts, test/domain/upm-config.test.ts, tsconfig.json
This change enables the `exactOptionalPropertyTypes` option in tsconfig. Also refactors code to work with this change.
This will give more security to prevent exporting explicit undefineds into external files.
=> refactor: enable exact optionals

src/cli/cmd-deps.ts, src/cli/dependency-logging.ts, src/domain/dependency-graph.ts, test/cli/cmd-deps.test.ts, test/cli/dependency-logging.test.ts
This overhauls the output for the deps command as discussed in #366.
New output sample:
=> feat: add new deps output

src/domain/package-manifest.ts, src/domain/packument.ts, src/domain/project-manifest.ts, test/cli/cmd-view.test.ts, test/domain/data-packument.ts
When designing some of the types which represent external data, we added all properties which exist in that data even when we don't use them.  This makes interacting and mocking these data types more difficult than it needs to be.
This change removes these properties since they have no impact on the app at all.
=> refactor: remove unused properties

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-remove.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts, src/cli/error-logging.ts, src/cli/index.ts, src/cli/options.ts, src/index.ts
This change shrinks `cli/index.ts`. Composition root and other global app setup was moved into `index.ts`. Logic for each command was moved into the corresponding cmd file. This is in preparation for overhauling the option logic which in itself is in preparation for #397.
=> refactor: shrink cli index

README.md, src/app/add-dependencies.ts, src/cli/cmd-add.ts, src/cli/dependency-logging.ts, src/cli/opt-registry.ts, test/e2e/add.test.ts, test/integration/app/add-dependencies.test.ts
This allows users to use any number of upstream registries when resolving packages.
See #349.
=> feat: multiple upstreams

src/index.ts, src/io/registry.ts, test/integration/app/add-dependencies.test.ts, test/integration/app/resolve-dependencies.test.ts, test/integration/io/registry.test.ts
Currently we use `another-npm-registry-client` for fetching packuments. This is a fork of a deprecated library. This change instead uses the currently maintained library for fetching packuments that is maintained by npm Just to modernize the dependencies a bit.
=> refacor: packument fetch

README.md, src/cli/error-logging.ts, src/domain/package-reference.ts, src/domain/packument.ts, src/domain/semantic-version.ts, test/common/data-packument.ts, test/unit/domain/packument.test.ts
Adds the "stable" tag. Users can now exclude pre-release versions when installing packages.
This should fix #395.
=> feat: stable tag

src/app/add-dependencies.ts, src/app/get-registry-packument-version.ts, src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-remove.ts, src/cli/cmd-view.ts, src/cli/dependency-logging.ts, src/cli/error-logging.ts, src/cli/validators.ts, src/domain/dependency-graph.ts, src/domain/package-spec.ts, src/domain/packument.ts, test/e2e/add.test.ts, test/unit/cli/dependency-logging.test.ts, test/unit/domain/package-spec.test.ts
After looking at the npm documentation, seems like the term for a package-name with or without version is called a "package spec"
https://docs.npmjs.com/cli/v8/using-npm/package-spec
Renamed relevant symbols to match this term
=> refactor: rename symbols

src/cli/cmd-add.ts, src/cli/cmd-deps.ts, src/cli/cmd-login.ts, src/cli/cmd-remove.ts, src/cli/cmd-search.ts, src/cli/cmd-view.ts
This PR makes some slight adjustments to the cli to make it closer to the npm cli. Mostly this means rewriting help messages, adding aliases and renaming arguments.
=> feat: make cli closer to npm

README.md, docs/cmd-ls.md, src/cli/cmd-ls.ts, src/cli/index.ts, test/e2e/ls.test.ts
This PR adds the `list` command. It behaves like calling `npm ls` without an argument and lists all installed dependencies.
See #351
=> feat: add list cmd

src/domain/domain-name.ts, test/unit/domain/domain-name.test.ts
Update domain name validation regex to permit underscores in domain segments, expanding support for package naming conventions. Fixed #420
=> fix: allow underscores in domain name segments
